title: Project Waterfall
subtitle: AI Storytelling

email: ksavela@umich.edu
instagram_url: https://instagram.com/bookishfreedom
linkedin_url: https://www.linkedin.com/in/kaylina-savela-2451b0151/

theme: jekyll-theme-cayman
